CREATE DATABASE IF NOT EXISTS baby;

GRANT SELECT, INSERT, UPDATE, DELETE ON baby.* TO 'baby'@'localhost';


CREATE TABLE IF NOT EXISTS baby.babies( 
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    name VARCHAR(20) 
);

CREATE TABLE IF NOT EXISTS baby.weights( 
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    baby_id INT NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    weight DOUBLE NOT NULL,
    INDEX (baby_id),
    FOREIGN KEY (baby_id)
      REFERENCES babies(id)
      ON DELETE CASCADE
);
